# Generated by Django 3.2.24 on 2024-02-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='charcode',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
